"""create words and user_word_stats tables

Revision ID: 1de47e7b3cb6
Revises: f2c04678b637
Create Date: 2025-10-22 18:02:35.437553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de47e7b3cb6'
down_revision: Union[str, Sequence[str], None] = 'f2c04678b637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
