"""add new table

Revision ID: c1c918370581
Revises: 571a2b9de9bc
Create Date: 2025-10-23 12:27:37.982403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c918370581'
down_revision: Union[str, Sequence[str], None] = '571a2b9de9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'frequency')
    op.drop_column('words', 'complexity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('complexity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
