"""Make user_activities.id auto-increment

Revision ID: fe1b0efe3141
Revises: c1c918370581
Create Date: 2025-10-26 04:36:00.009610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1b0efe3141'
down_revision: Union[str, Sequence[str], None] = 'c1c918370581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_activities', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_activities', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('user_activities_user_id_fkey'), 'user_activities', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_activities_user_id_fkey'), 'user_activities', 'users', ['user_id'], ['id'])
    op.alter_column('user_activities', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_activities', 'word_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_activities', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
